from src.models.fastapi_answer import get_model_by_prompt_fastapi
from src.models.flutter_answer import get_model_by_prompt_flutter
from src.models.text_to_json import get_model_text_to_json
from src.models.json_to_text import get_model_json_to_text
from src.models.prompt_test import get_model_by_prompt_test
from src.models.tulu3 import get_model_by_tulu3
from src.models.tulu3_langchain import get_model_by_tulu3_langchain