from src.models.flutter import get_model_by_prompt_flutter
from src.models.express_typescript import get_model_by_prompt_express_typescript
from src.models.text_to_json import get_model_text_to_json
from src.models.json_to_text import get_model_json_to_text
from src.models.tulu3 import get_model_by_tulu3
from src.models.tulu3_langchain import get_model_by_tulu3_langchain
from src.models.landingpage import get_model_by_landing_page